In [ ]:
#sijisha paul_25070123138
#data binning and data formatting using python

In [2]:
import pandas as pd
import numpy as np
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15]
}
df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [4]:
#Data Binning
bins1= [0,10000,30000,60000]
labels1=['Low','Medium','High']
df['Price_Category']=pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [6]:
#Binning Units Sold
bins2=[0,30,60,100]
labels2=['Low Sales','Medium Sales','High Sales']
df['Sales_Category']=pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [7]:
#data formatting
#convert data type
print(df.dtypes)
#df['Units_Sold']=df['Units_Sold'].astype(float)
#print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

In [8]:
#convert data type
print(df.dtypes)
df['Units_Sold']=df['Units_Sold'].astype(float)
print(df.dtypes)
df

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0         Medium   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera  45000        15.0           High      Low Sales

In [9]:
#convert text to uppercase
df['Product']=df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [10]:
#rounding values
df['price']=df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category  price
0      LAPTOP  55000        25.0           High      Low Sales  55000
1      MOBILE  20000        60.0         Medium   Medium Sales  20000
2      TABLET  30000        35.0         Medium   Medium Sales  30000
3  HEADPHONES   2000        80.0            Low     High Sales   2000
4  SMARTWATCH   8000        50.0            Low   Medium Sales   8000
5      CAMERA  45000        15.0           High      Low Sales  45000

In [11]:
#additional operations
#sort data
sorted_df=df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category Sales_Category  price
3  HEADPHONES   2000        80.0            Low     High Sales   2000
4  SMARTWATCH   8000        50.0            Low   Medium Sales   8000
1      MOBILE  20000        60.0         Medium   Medium Sales  20000
2      TABLET  30000        35.0         Medium   Medium Sales  30000
5      CAMERA  45000        15.0           High      Low Sales  45000
0      LAPTOP  55000        25.0           High      Low Sales  55000

In [12]:
df.sort_values(by='Price',ascending=False,inplace=True)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category  price
0      LAPTOP  55000        25.0           High      Low Sales  55000
5      CAMERA  45000        15.0           High      Low Sales  45000
2      TABLET  30000        35.0         Medium   Medium Sales  30000
1      MOBILE  20000        60.0         Medium   Medium Sales  20000
4  SMARTWATCH   8000        50.0            Low   Medium Sales   8000
3  HEADPHONES   2000        80.0            Low     High Sales   2000

In [13]:
#display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [14]:
#Dataset: Food delivery orders
import pandas as pd
import numpy as np
data={
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_km':[5,8,3,10,6,2,9,4]
}
df=pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [15]:
#Binning Order Value
bins=[0,200,400,700]
labels=['Low Order','Medium Order','High Order']
df['Order_Category']=pd.cut(df['Order_Value'],bins=bins,labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [16]:
#Binning Delivery Time
bins2=[0,30,45,70]
labels2=['Fast','Normal','Slow']
df['Delivery_Category']=pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

  Delivery_Category
0              Fast
1            Normal
2              Fast
3              Slow
4            Normal
5              Fast
6              Slow
7              Fast

In [17]:
#count of categories
print(df['Order_Category'].value_counts())
df

Order_Category
Medium Order    3
High Order      3
Low Order       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5,Medium Order,Fast
1,02,450,45,8,High Order,Normal
2,03,120,25,3,Low Order,Fast
3,04,600,60,10,High Order,Slow
4,05,300,35,6,Medium Order,Normal
5,06,150,20,2,Low Order,Fast
6,07,500,50,9,High Order,Slow
7,08,220,28,4,Medium Order,Fast

In [18]:
#convert Oder_ID to uppercase
df['Order_ID']=df['Order_ID'].str.upper()
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

  Delivery_Category
0              Fast
1            Normal
2              Fast
3              Slow
4            Normal
5              Fast
6              Slow
7              Fast